### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by comeradealexi**
If these pointers aren't zero, then the sample will crash.

Test for yourself by putting a random value into these pointers.

### CODE REVIEW

**Comment by tdaede** [comment]
Global variables are initialized to zero in C. Is there any real-world case where you hit this bug?

**Comment by comeradealexi** [comment]
Ah, interesting. I was using parts of the sample program to put into a C++ project, I never knew this difference existed between C++ and C!

Might help others like myself being caught out in the future if it was explicitly initialised, even though it's not a C bug :)

Alex

**Comment by rillian** [comment]
IIRC there are other issues with compiling theora as C++ instead of C. Perhaps we should
```C
#if defined(__cplusplus)
#error Theora must be compiled as C, not C++!
#endif
```
everywhere?

**Review by rillian — APPROVED** [review]
On the other hand, no reason to be confusing in the example code.

**Comment by rillian** [comment]
Applied with corresponding changes to the other examples and an updated commit message in 91203fdfdc0eb06cd87409d47e35d9ee5471a90f.

**Pull request closed without merging**
